services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./pyproject.toml
          action: rebuild
          target: /app/pyproject.toml
    restart: on-failure
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations

  worker:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile

    restart: on-failure:3
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
    command:
      ["/app/.venv/bin/arq", "app.entrypoints.workers.setup.WorkerSettings"]

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - 8004:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  # cloudbeaver_data:
  pgdata:
