"""relationship updated

Revision ID: 256391f1b255
Revises: 2c92e8c13eea
Create Date: 2026-05-11 15:23:36.223852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256391f1b255'
down_revision: Union[str, Sequence[str], None] = '2c92e8c13eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transaction_reference_id_fkey'), 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'product', ['reference_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_reference_id_fkey'), 'transaction', 'product', ['reference_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
