FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    git \
    libsndfile1 \
    ffmpeg \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

RUN uv pip install --system fastapi[standard] coqui-tts[bn,ja,zh] pydub python-iso639 pedalboard


ENV COQUI_TOS_AGREED=1
ENV MECABRC=/etc/mecabrc

COPY dockerfiles/service_resources/custom_tts_server.py .
COPY dockerfiles/service_resources/tts_schemas.py .

# obfuscation steps
RUN uv pip install --system pyarmor
RUN pyarmor gen --output dist custom_tts_server.py tts_schemas.py
RUN mv dist/* . && rm -rf dist
# done obfuscation
EXPOSE 8020

#CMD ["uvicorn", "custom_tts_server:app", "--host", "0.0.0.0", "--port", "8020"]
CMD ["python", "custom_tts_server.py"]