FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    git \
    libsndfile1 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

RUN uv pip install --system \
    fastapi[standard] \
    coqui-tts==0.26.2 \
    transformers==4.48.3 \
    torch==2.4.1 \
    torchaudio==2.4.1 \
    pydub==0.25.1 \
    python-iso639==2026.1.31 \
    pedalboard==0.9.22

# RUN pip install --no-cache-dir fastapi[standard] coqui-tts pydub

ENV COQUI_TOS_AGREED=1
ENV MECABRC=/etc/mecabrc

COPY dockerfiles/service_resources/custom_tts_server.py .
COPY dockerfiles/service_resources/tts_schemas.py .

EXPOSE 8020

CMD ["uvicorn", "custom_tts_server:app", "--host", "0.0.0.0", "--port", "8020"]
