"""relationship with ondelete operations

Revision ID: 2c92e8c13eea
Revises: 4195659da757
Create Date: 2026-05-11 12:10:48.169431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c92e8c13eea'
down_revision: Union[str, Sequence[str], None] = '4195659da757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transaction_reference_id_fkey'), 'transaction', type_='foreignkey')
    op.drop_constraint(op.f('transaction_wallet_id_fkey'), 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'product', ['reference_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transaction', 'wallet', ['wallet_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('usersession_user_id_fkey'), 'usersession', type_='foreignkey')
    op.create_foreign_key(None, 'usersession', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('wallet_user_id_fkey'), 'wallet', type_='foreignkey')
    op.create_foreign_key(None, 'wallet', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.create_foreign_key(op.f('wallet_user_id_fkey'), 'wallet', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'usersession', type_='foreignkey')
    op.create_foreign_key(op.f('usersession_user_id_fkey'), 'usersession', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_wallet_id_fkey'), 'transaction', 'wallet', ['wallet_id'], ['id'])
    op.create_foreign_key(op.f('transaction_reference_id_fkey'), 'transaction', 'product', ['reference_id'], ['id'])
    # ### end Alembic commands ###
