"""multiple session

Revision ID: 8bc68f1f9e6f
Revises: a302d9a9a0ae
Create Date: 2026-05-24 05:13:50.335508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bc68f1f9e6f'
down_revision: Union[str, Sequence[str], None] = 'a302d9a9a0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersession', sa.Column('id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('usersession_user_id_key'), 'usersession', type_='unique')
    op.create_index(op.f('ix_usersession_user_id'), 'usersession', ['user_id'], unique=False)
    op.drop_column('usersession', 'last_activity_at')
    op.drop_column('usersession', 'session_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersession', sa.Column('session_token', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('usersession', sa.Column('last_activity_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_usersession_user_id'), table_name='usersession')
    op.create_unique_constraint(op.f('usersession_user_id_key'), 'usersession', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('usersession', 'id')
    # ### end Alembic commands ###
