"""product relationship modified

Revision ID: a302d9a9a0ae
Revises: a07a5bb9872a
Create Date: 2026-05-12 10:42:11.178063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a302d9a9a0ae'
down_revision: Union[str, Sequence[str], None] = 'a07a5bb9872a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('product_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('transaction_reference_id_fkey'), 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'product', ['product_id'], ['id'])
    op.drop_column('transaction', 'reference_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_reference_id_fkey'), 'transaction', 'product', ['reference_id'], ['id'])
    op.drop_column('transaction', 'product_id')
    # ### end Alembic commands ###
